#!/usr/bin/env bash
# scripts/subset-fonts.sh — download + subset + self-host the Google
# Fonts FortuneFallacy uses, dropping the runtime Google CDN dependency.
#
# Why: the current `@import` in `src-next/styles/index.css` pulls four
# font families (Cinzel Decorative, Cinzel, Exo 2, JetBrains Mono) at
# multiple weights from Google's CDN. That's ~12 font-face requests +
# ~200-400 KB blocking first paint on a slow connection.
#
# This script:
#   1. Downloads the woff2 source files from the Google Fonts API.
#   2. Subsets each to just the glyphs actually used by the game
#      (Latin + numerals + a handful of named glyphs from the data
#      files - currency, dice pips, math symbols, etc.).
#   3. Drops the results in `public/fonts/`.
#   4. Prints the CSS @font-face block to paste into index.css and the
#      @import line to remove.
#
# Usage:
#   bash scripts/subset-fonts.sh
#
# Requirements:
#   - python3 with `fonttools` (>=4.0). Install with:
#       python3 -m pip install --user fonttools brotli
#   - curl (or wget) for the font downloads.
#
# Run after the audit-screenshots / final visual pass so any newly-used
# glyphs land in the subset; re-run any time a new visible glyph is added.

set -euo pipefail
cd "$(dirname "$0")/.."

PUBLIC_FONTS="public/fonts"
mkdir -p "$PUBLIC_FONTS"

if ! command -v pyftsubset >/dev/null 2>&1; then
  echo "error: pyftsubset (from fontTools) not found on PATH" >&2
  echo "       install with: python3 -m pip install --user fonttools brotli" >&2
  exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "error: curl not found" >&2
  exit 1
fi

# Allowed glyphs - Latin basic + Latin-1 supplement (common typographic
# punctuation + accents) + numerals + a few named glyphs surfaced by the
# game's catalyst / mod / boss icons (currency symbol, infinity, etc.).
# Add to this set as new glyphs ship.
UNICODES="U+0020-007E,U+00A0-00FF,U+2013-2014,U+2018-201D,U+2022,U+2026,U+221E,U+0394,U+00D7,U+00B0,U+25C6"

download_and_subset() {
  local family="$1"
  local weights="$2"
  local file_prefix="$3"

  # Use the Google Fonts CSS endpoint to discover the actual woff2 URLs.
  local css_url
  css_url="https://fonts.googleapis.com/css2?family=$(printf '%s' "$family" | tr ' ' '+'):wght@${weights}&display=swap"
  local css
  css=$(curl -sSL -A "Mozilla/5.0" "$css_url")

  # Pull every src URL.
  echo "$css" | grep -oE 'https://fonts\.gstatic\.com/[^)]*\.woff2' | sort -u | while read -r url; do
    local weight
    weight=$(echo "$css" | awk -v u="$url" '/font-weight/ { w=$2 } $0 ~ u { gsub(/[;,]/, "", w); print w; exit }')
    local raw="$PUBLIC_FONTS/${file_prefix}-${weight}.raw.woff2"
    local out="$PUBLIC_FONTS/${file_prefix}-${weight}.woff2"
    echo "  ${family} ${weight} -> ${out##*/}"
    curl -sSL -o "$raw" "$url"
    pyftsubset "$raw" \
      --unicodes="$UNICODES" \
      --flavor=woff2 \
      --layout-features='*' \
      --output-file="$out"
    rm -f "$raw"
  done
}

echo "downloading + subsetting fonts..."
download_and_subset "Cinzel Decorative" "400;700;900" "cinzel-decorative"
download_and_subset "Cinzel"            "400;500;600;700" "cinzel"
download_and_subset "Exo 2"             "300;400;500;700" "exo2"
download_and_subset "JetBrains Mono"    "400;500;700"     "jetbrains-mono"

echo
echo "done. wrote subset files to $PUBLIC_FONTS:"
ls -lh "$PUBLIC_FONTS"/*.woff2 2>/dev/null

cat <<'CSS'

==============================================================================
CSS update required in src-next/styles/index.css

Remove the current Google Fonts @import line at the top of the file and
replace with the @font-face block below (pointing at the self-hosted files).
The @import was:
  @import url('https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700;900&family=Cinzel:wght@400;500;600;700&family=Exo+2:ital,wght@0,300;0,400;0,500;0,700;1,400&family=JetBrains+Mono:wght@400;500;700&display=swap');

Replace with:

/* Self-hosted, subsetted Google Fonts. Generated by scripts/subset-fonts.sh. */
@font-face { font-family: 'Cinzel Decorative'; font-weight: 400; font-style: normal;
  src: url('/FortuneFallacy/fonts/cinzel-decorative-400.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Cinzel Decorative'; font-weight: 700; font-style: normal;
  src: url('/FortuneFallacy/fonts/cinzel-decorative-700.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Cinzel Decorative'; font-weight: 900; font-style: normal;
  src: url('/FortuneFallacy/fonts/cinzel-decorative-900.woff2') format('woff2'); font-display: swap; }

@font-face { font-family: 'Cinzel'; font-weight: 400; font-style: normal;
  src: url('/FortuneFallacy/fonts/cinzel-400.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Cinzel'; font-weight: 500; font-style: normal;
  src: url('/FortuneFallacy/fonts/cinzel-500.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Cinzel'; font-weight: 600; font-style: normal;
  src: url('/FortuneFallacy/fonts/cinzel-600.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Cinzel'; font-weight: 700; font-style: normal;
  src: url('/FortuneFallacy/fonts/cinzel-700.woff2') format('woff2'); font-display: swap; }

@font-face { font-family: 'Exo 2'; font-weight: 300; font-style: normal;
  src: url('/FortuneFallacy/fonts/exo2-300.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Exo 2'; font-weight: 400; font-style: normal;
  src: url('/FortuneFallacy/fonts/exo2-400.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Exo 2'; font-weight: 500; font-style: normal;
  src: url('/FortuneFallacy/fonts/exo2-500.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'Exo 2'; font-weight: 700; font-style: normal;
  src: url('/FortuneFallacy/fonts/exo2-700.woff2') format('woff2'); font-display: swap; }

@font-face { font-family: 'JetBrains Mono'; font-weight: 400; font-style: normal;
  src: url('/FortuneFallacy/fonts/jetbrains-mono-400.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'JetBrains Mono'; font-weight: 500; font-style: normal;
  src: url('/FortuneFallacy/fonts/jetbrains-mono-500.woff2') format('woff2'); font-display: swap; }
@font-face { font-family: 'JetBrains Mono'; font-weight: 700; font-style: normal;
  src: url('/FortuneFallacy/fonts/jetbrains-mono-700.woff2') format('woff2'); font-display: swap; }

==============================================================================
CSS
